name: ${NAME}
version: ${VERSION}
api-version: ${MINECRAFT_VERSION}
main: ru.joutak.template.JoyBankPlugin
description: 'A template plugin'
authors: ['russlan_1esse']
contributors: ['technosimp']
website: ${WEBSITE}

depend: []
libraries:
  - 'org.projectlombok:lombok:${LOMBOK_VERSION}'
commands:
  joy:
    description: Основная команда JoyBank
    usage: /joy

permissions:
  joybank.admin.give:
    description: Позволяет выдавать монеты Джой
    default: op
  joybank.atm.create:
    description: Позволяет создавать банкоматы
    default: op
  joybank.atm.break:
    description: Позволяет удалять зарегистрированные банкоматы
    default: op